# Generated by Django 5.2.1 on 2025-05-14 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('generic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('usage', models.TextField()),
                ('side_effects', models.TextField(blank=True, null=True)),
                ('contraindications', models.TextField(blank=True, null=True)),
                ('dosage_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('USER', 'User Message'), ('BOT', 'Bot Message')], max_length=4)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('DOCTOR', 'Doctor Recommendation'), ('HOSPITAL', 'Hospital Recommendation'), ('EMERGENCY', 'Emergency Advice'), ('SELF_CARE', 'Self Care Advice'), ('MEDICATION', 'Medication Information')], max_length=15)),
                ('content', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0, help_text='Between 0 and 1, 1 being most confident')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitals.doctor')),
                ('recommended_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitals.hospitalprofile')),
                ('recommended_specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitals.specialization')),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='chatbot.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('specializations', models.ManyToManyField(related_name='diseases', to='hospitals.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('severity_level', models.PositiveSmallIntegerField(default=1, help_text='1-5 scale, 5 being most severe')),
                ('related_specializations', models.ManyToManyField(related_name='symptoms', to='hospitals.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_strength', models.FloatField(default=0.5, help_text='Between 0 and 1, 1 being strongest')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.disease')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.symptom')),
            ],
            options={
                'unique_together': {('disease', 'symptom')},
            },
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.ManyToManyField(related_name='diseases', through='chatbot.DiseaseSymptom', to='chatbot.symptom'),
        ),
        migrations.CreateModel(
            name='PatientSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('severity_reported', models.PositiveSmallIntegerField(default=3, help_text='1-5 scale, 5 being most severe')),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_symptoms', to='chatbot.chatsession')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.symptom')),
            ],
            options={
                'unique_together': {('chat_session', 'symptom')},
            },
        ),
    ]
