# Generated by Django 5.0.1 on 2025-08-24 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possible_diseases', models.JSONField(default=list, help_text='List of possible diseases with confidence scores')),
                ('confidence_score', models.FloatField(default=0.0)),
                ('urgency_level', models.CharField(choices=[('LOW', 'Low Urgency'), ('MEDIUM', 'Medium Urgency'), ('HIGH', 'High Urgency'), ('EMERGENCY', 'Emergency - Seek immediate care')], default='MEDIUM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_diagnoses', to='chatbot.chatsession')),
                ('primary_diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.disease')),
                ('symptoms', models.ManyToManyField(related_name='ai_diagnoses', to='chatbot.symptom')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('CRITICAL_VITALS', 'Critical Vital Signs'), ('SEVERE_SYMPTOMS', 'Severe Symptoms'), ('IMAGE_ANOMALY', 'Critical Image Finding'), ('SYMPTOM_COMBINATION', 'Dangerous Symptom Combination')], max_length=25)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_alerts', to='chatbot.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='HealthMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure_systolic', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.PositiveIntegerField(blank=True, null=True)),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('blood_sugar', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to='chatbot.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='medical_images/')),
                ('image_type', models.CharField(choices=[('XRAY', 'X-Ray'), ('MRI', 'MRI Scan'), ('CT', 'CT Scan'), ('ULTRASOUND', 'Ultrasound'), ('BLOOD_REPORT', 'Blood Report'), ('PATHOLOGY', 'Pathology Report'), ('ECG', 'ECG Report'), ('OTHER', 'Other Medical Report')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_images', to='chatbot.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_text', models.TextField()),
                ('detected_conditions', models.JSONField(default=list, help_text='List of detected medical conditions')),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence in the analysis (0-1)')),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('medical_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='chatbot.medicalimage')),
            ],
        ),
    ]
