# Generated by Django 5.0.1 on 2025-08-29 02:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitalprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hospital Profile', 'verbose_name_plural': 'Hospital Profiles'},
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes for approval/rejection', null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_hospitals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin approval status'),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if any', null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='unique_hospital_id',
            field=models.CharField(blank=True, help_text='Unique ID assigned by admin', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
