# Generated by Django 5.0.1 on 2025-09-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_add_csv_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofile',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
